#!/bin/bash

#detect chroot
if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/. 2>/dev/null)" ]; then
  touch /run/noreboot
  touch /run/noreboot-chroot
fi

sysctl -w vm.dirty_expire_centisecs=2000 > /dev/null 2>&1
sysctl -w vm.dirty_writeback_centisecs=500 > /dev/null 2>&1
sysctl -w vm.min_free_kbytes=24576 > /dev/null 2>&1

for groupname in audio input; do
    if [ "0$(grep ^$groupname\: /etc/group | awk -F':' '{print $3}')" -ge 1000 ]; then
        newgid="$(($(grep '.*\:[0-9][0-9][0-9]\:.*' /etc/group | awk -F':' '{print $3}' | sort | tail -1) + 1))"
        groupmod -g $newgid $groupname >/dev/null 2>&1 || :
    fi
done

#{ mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
if ! test -e /run/noreboot-chroot && grep -wq /boot /etc/fstab; then
    mountpoint -q /boot || mount /boot || exit 1
fi

if [ $1 == "install" -o $1 == "upgrade" ]; then

        if ! pgrep xbmc.bin >/dev/null && ! pgrep kodi.bin >/dev/null && { [ ! -e /run/lock/xbian-config.gui ] || [ $(grep -c . /run/lock/xbian-config.gui 2>/dev/null) -eq 0 ]; }; then

            pkill splash || :; pkill splash-daemon || :

            [ -e /run/nosplash -o -e /run/noreboot ] || /usr/bin/splash --infinitebar --msgtxt="installing update..." &
        else
            touch /run/noreboot
        fi

        if [ -f "/boot/cmdline.txt" ]; then
            mv /boot/cmdline.txt /boot/cmdline.txt.old
        fi
        [ ! -e "/boot/cmdline.new" ] || rm -f /boot/cmdline.new

        [ ! -e /etc/xbian_revision ] || cp /etc/xbian_revision /tmp/xbian_revision.old

        version=$(printf "%.4s" $(dpkg-query -W -f='${Version}\n' "xbian-update" 2>/dev/null| sed 's/[\.-]//g')) 
        echo "version=$version" > /tmp/xbian-update-prev.ver

        if [ ! -e /etc/samba/smb.conf.xbian ]; then
            mv /etc/samba/smb.conf /etc/samba/smb.conf.xbian
        fi
fi
