#!/bin/bash

sysctl -w vm.dirty_expire_centisecs=2000 > /dev/null
sysctl -w vm.dirty_writeback_centisecs=500 > /dev/null
sysctl -w vm.min_free_kbytes=24576 > /dev/null

#{ mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
mountpoint -q /boot || mount /boot || exit 1

if [ $1 == "install" -o $1 == "upgrade" ]; then

        sed -i 's/^initramfs /#initramfs /' /boot/config.txt

        if ! pgrep xbmc.bin > /dev/null && { [ ! -e /run/lock/xbian-config.gui ] || [ $(grep -c . /run/lock/xbian-config.gui 2>/dev/null) -eq 0 ]; }; then

            pkill splash || :

            [ -e /run/nosplash ] || /usr/bin/splash --infinitebar --msgtxt="installing update..." &
        else
            touch /run/noreboot
        fi

	if [ -f "/boot/cmdline.txt" ]; then
		mv /boot/cmdline.txt /boot/cmdline.txt.old
	fi
	[ ! -e "/boot/cmdline.new" ] || rm -f /boot/cmdline.new

	[ ! -e /etc/xbian_revision ] || cp /etc/xbian_revision /tmp/xbian_revision.old

        version=$(printf "%.4s" $(dpkg-query -W -f='${Version}\n' "xbian-update" 2>/dev/null| sed 's/[\.-]//g')) 
        echo "version=$version" > /tmp/xbian-update-prev.ver

        if [ ! -e /etc/samba/smb.conf.xbian ]; then
            mv /etc/samba/smb.conf /etc/samba/smb.conf.xbian
        fi
fi

