#!/bin/bash

mountpoint -q /boot || mount /boot

if [ $1 == "install" -o $1 == "upgrade" ]; then

        insserv -fr xbian-waiter > /dev/null 2>&1

        if ! test -e /run/noreboot; then
            stop xbmc >/dev/null 2>&1|| service xbmc stop >/dev/null 2>&1||true

            pkill splash || :

            /usr/bin/splash --infinitebar --msgtxt="installing update..." &
        fi

	if [ -f "/boot/cmdline.txt" ]; then
		mv /boot/cmdline.txt /boot/cmdline.txt.old
	fi
	[ ! -e "/boot/cmdline.new" ] || rm -f /boot/cmdline.new

	[ ! -e /etc/xbian_revision ] || cp /etc/xbian_revision /tmp/xbian_revision.old
fi
