#! /bin/sh
### BEGIN INIT INFO
# Provides:          frandom
# Required-Start:    kmod
# Required-Stop:     
# Default-Start:     S 
# Default-Stop:      0 1 6
# Short-Description: Initialize frandom and erandom
# Description:
### END INIT INFO
#
# Author: CurlyMoo <development@xbian.org>
#

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
	test -e /dev/frandom || { log_error_msg "failed"; exit 1; }
	[ ! -e /dev/urandom.orig ] && mv /dev/urandom /dev/urandom.orig || true
	[ -e /dev/urandom ] && rm /dev/urandom || true
	ln -s /dev/frandom /dev/urandom

	test -e /dev/erandom || { log_error_msg "failed"; exit 1; }
	[ ! -e /dev/random.orig ] && mv /dev/random /dev/random.orig || true
	[ -e /dev/random ] && rm /dev/random || true
	ln -s /dev/erandom /dev/random
        log_success_msg "frandom loaded"
	;;
  stop)
	test -e /dev/urandom.orig && mv /dev/urandom.orig /dev/urandom
	test -e /dev/random.orig && mv /dev/random.orig /dev/random
        log_success_msg "frandom unloaded"
	;;
  restart)
	stop
	sleep 1
	start
        log_success_msg "frandom restarted"
	;;
  *)
	log_warning_msg "Usage: /etc/init.d/frandom {start|stop|restart}" >&2
	exit 3
	;;
esac

exit 0

