#!/bin/sh

### BEGIN INIT INFO
# Provides:          xbian-waiter
# Required-Start:    
# Required-Stop:     sendsigs
# Default-Start:
# Default-Stop:      0 6
# Comment:      
### END INIT INFO

case $(runlevel | awk '{print $2}') in
    0)
        start xbian-waiter WAIT_FOR=progress-shutdown WAITER=initd WAIT_STATE="running" 
        ;;
    6)
        start xbian-waiter WAIT_FOR=progress-reboot WAITER=initd WAIT_STATE="running" 
        ;;
    *)
        ;;
esac

exit 0

