#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ ! -e /run/motd.dynamic ] || \
	[ $(stat --print=%Y /run/motd.dynamic) -le "$(stat --print=%Y /var/lib/apt/periodic/update-success-stamp 2>/dev/null|| echo 9999999999)" ] ||exit 0
exec > /run/motd.dynamic
uname -snrv 
/bin/echo -e "\e[5m$(nr=$(xbian-apt-show-versions -u | grep -c .); [ $nr -ne 0 ] && { echo; echo $nr packages can be updated; } )\e[25m
"
