#!/bin/sh

stop xbmc
rm -f /home/xbian/*.log
rm -f /home/xbian/.xbmc/temp/*.log /home/xbian/.kodi/temp/*.log
for f in $(find /var/log -type f); do echo > $f; done
find / -xdev -iname \*.DS_Store | xargs rm -f
rm /boot/*.old
apt-get autoclean
apt-get autoremove
apt-get clean
rm -f /home/xbian/.bash_history
rm -fr /home/xbian/.cache
rm -fr /home/xbian/.local
rm -fr /home/xbian/.config
rm -f /root/.bash_history
rm -fr /root/.cache
rm -fr /root/.local
rm -fr /root/.config
rm -f /etc/apt/preferences.d/media
rm -fr /home/xbian/.mc
rm -fr /root/.mc
rm -fr /root/.ssh
rm -fr /home/xbian/.ssh
mountpoint -q /run || rm -fr /run/*
rm -fr /tmp/*
rm -fr /var/tmp/*
rm -f /var/lib/dpkg/*-old
rm -f /var/cache/debconf/*-old
rm -fr /home/xbian/.xbmc/userdata/addon_data/plugin.xbianconfig /home/xbian/.kodi/userdata/addon_data/plugin.xbianconfig
rm -f /home/xbian/.xbian-config-start
echo 1 > /home/xbian/.xbian-config-start; chown xbian:xbian /home/xbian/.xbian-config-start
sed -i 's/<systemtotaluptime>.*<\/systemtotaluptime>/<systemtotaluptime>0<\/systemtotaluptime>/g' /home/xbian/.xbmc/userdata/guisettings.xml >/dev/null 2>&1
sed -i 's/<systemtotaluptime>.*<\/systemtotaluptime>/<systemtotaluptime>0<\/systemtotaluptime>/g' /home/xbian/.kodi/userdata/guisettings.xml >/dev/null 2>&1
rm /etc/ssh/ssh_host_*
history -c
umount /mnt/*
rmdir /mnt/*
