#!/bin/sh

env >> /run/xbian-udhcpc.$IFACE
echo "command parameters $@" >> /run/xbian-udhcpc.$IFACE

while test $# -ne '0'; do
    case $1 in
        -n)
            shift
            ;;
        -p)
            PID=$2
            shift 2
            ;;
        -i)
            shift 2
            ;;
        -H)
            dhcp_hostname=$2
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

[ -n "$PID" ] || PID=/run/udhcpc.$IFACE.pid

trap '' USR2
pidfile=$PID interface=$IFACE dhcp_hostname=$dhcp_hostname \
    /etc/xbian-udhcpc/xbian-dhcp bound & echo $! > $PID
wait $!
exit $?
