#!/bin/sh
# Xbian dhcp script.
#
# Based on the busybox example scripts

RESOLV_CONF="/etc/resolv.conf"
. /etc/xbian-initramfs/cnvres-code.sh 

ifdwn() {
    ip link set ${interface} down || :
    return 0
}

case $1 in
    bound|renew)

        ip link set ${interface} up || :

        [ -z "$METHOD" ] && METHOD=dhcp
        echo DHCPDISCOVER >&2
        ipconfig -t 60 -d $interface -c $METHOD 1>&2
        [ $? -eq 124 ] && { echo Terminated >&2; ip link set $interface down || :; exit 1; }
        echo bound >&2

        R=$(update_resolv)
        if echo $R | grep -q nameserver; then 
            if [ -x /sbin/resolvconf ]; then
                echo "$R" | resolvconf -a "${interface}.udhcpc"
            else
                echo "$R" > "$RESOLV_CONF"
            fi
        fi
        leasetime=$(cat /run/net-$interface.conf | grep DHCPLEASETIME | awk -F'=' '{print $2}' |tr -d "'")
        if grep -q 127.0.2.1 /etc/hosts; then
            sed -i "s%127.0.2.1.*%127.0.2.1 $(hostname)%" /etc/hosts
        else
            echo "127.0.2.1 $(hostname)" >> /etc/hosts
        fi
	;;

    deconfig)
	interface=${interface} ifdwn
	if [ -x /sbin/resolvconf ]; then
	    resolvconf -d "${interface}.udhcpc"
	fi
	#[ -f "$pidfile" ] && rm -fr $pidfile
	exit 0
	;;

    leasefail)
	echo "$0: Lease failed: $message"
	;;

    nak)
	echo "$0: Received a NAK: $message"
	;;

    slp)
        ;;

    *)
	echo "$0: Unknown udhcpc command: $1";
	exit 1;
	;;
esac


if [ $1 != slp ]; then
    pidfile=$pidfile interface=$interface leasetime=$leasetime $0 slp &
    exit 0
fi

trap 'ifdwn' USR2
sleep $leasetime & spid=$! && echo $spid > $pidfile

if wait "$spid"; then
    pidfile="$pidfile" interface="$interface" $0 renew &
else
    pds="$(cat /run/wpa_supplicant.$interface.pid 2>/dev/null)"; [ -z "$pds" ] || kill "$pds" || :
    rm -fr "/run/wpa_supplicant.$interface.pid"
    pidfile="$pidfile" interface="$interface" $0 deconfig
fi
