#!/bin/sh
# Xbian dhcp script.
#
# Based on the busybox example scripts

exec >> /run/xbian-udhcpc.$interface
echo "------"

RESOLV_CONF="/etc/resolv.conf"
. /etc/xbian-initramfs/cnvres-code.sh 

case $1 in
    bound|renew)

        case $METHOD in
            dhcp)
                echo DHCPDISCOVER >&2
                timeout 60 ipconfig -d $interface -c dhcp > /dev/null 2>&1
                [ $? -eq 124 ] && exit 1
                echo bound >&2
                ;;
            *)
                exit 0
                ;;
        esac

        R=$(update_resolv)
        if echo $R | grep -q nameserver; then 
            if [ -x /sbin/resolvconf ]; then
                echo "$R" | resolvconf -a "${interface}.udhcpc"
            else
                echo "$R" > "$RESOLV_CONF"
            fi
        fi
        leasetime=$(cat /run/net-$interface.conf | grep DHCPLEASETIME | awk -F'=' '{print $2}' |tr -d "'")
	;;

    deconfig)
	if [ -x /sbin/resolvconf ]; then
	    resolvconf -d "${interface}.udhcpc"
	fi
	[ -f "$pidfile" ] && rm -fr $pidfile
	exit 0
	;;

    leasefail)
	echo "$0: Lease failed: $message"
	;;

    nak)
	echo "$0: Received a NAK: $message"
	;;

    slp)
        ;;

    *)
	echo "$0: Unknown udhcpc command: $1";
	exit 1;
	;;
esac

if [ $1 != slp ]; then
    pidfile=$pidfile interface=$interface leasetime=$leasetime $0 slp &
    exit 0
fi

trap '' USR2
sleep $leasetime & spid=$!; echo $spid > $pidfile
echo Terminated >&2
if wait $spid; then
    pidfile=$pidfile interface=$interface $0 renew &
else
    kill $(cat /run/wpa_supplicant.$interface.pid) >/dev/null 2>&1
    rm -fr /run/wpa_supplicant.$interface.pid
    pidfile=$pidfile interface=$interface $0 deconfig
fi
